# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb5ea7d457ca6590d50b0847ff0d366d276434f9d2703881e7cbcf01d526262ec7097400e74bfae331efb93789fb95186987e3a22999addac83e949bfbf9fa73

test:
  secret_key_base: 441e715884490f71de670f89a4763c464ab74a4bae8d39d46d53dbbc390b956bdc217260b7f74915cb2d035a5e2dc3eaf6fbd9071eb617cdcd8ec22c963eb0ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
